"""empty message

Revision ID: 3771536672d8
Revises: 08df5f719d73
Create Date: 2020-01-19 16:23:33.409132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3771536672d8'
down_revision = '08df5f719d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_image', sa.String(length=100), nullable=True))
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'avatar_image')
    # ### end Alembic commands ###
