"""empty message

Revision ID: 918c0c6ff2ad
Revises: 3771536672d8
Create Date: 2020-01-20 12:20:18.061243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918c0c6ff2ad'
down_revision = '3771536672d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('cover_image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'cover_image')
    # ### end Alembic commands ###
